"""
Bureaucracy Service — orchestrates RAG + LLM + Firestore for chat turns.

Responsibilities:
- Conversation lifecycle (create, load, persist)
- Firestore reads/writes for conversation memory (via asyncio.to_thread)
- Assembling the RAG-augmented prompt and streaming LLM response
"""

import asyncio
import logging
import uuid
from datetime import datetime, timezone
from typing import AsyncIterator, Optional

from app.ai.llm_client import LLMClient, LLMClientError
from app.ai.rag_pipeline import RAGPipeline, BUREAUCRACY_SYSTEM_INSTRUCTION
from app.core.config import settings

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.ai.deadline_extractor import DeadlineExtractor
    from app.services.deadline_service import DeadlineService
    from app.ai.wellbeing_classifier import WellbeingClassifier
    from app.services.wellbeing_service import WellbeingService

logger = logging.getLogger(__name__)


class BureaucracyService:
    """Business logic orchestrator for the bureaucracy chat feature."""

    def __init__(
        self,
        rag_pipeline: RAGPipeline,
        llm_client: LLMClient,
        firestore_client,
        deadline_extractor: "DeadlineExtractor | None" = None,
        deadline_service: "DeadlineService | None" = None,
        wellbeing_classifier: "WellbeingClassifier | None" = None,
        wellbeing_service: "WellbeingService | None" = None,
    ):
        self._rag = rag_pipeline
        self._llm = llm_client
        self._db = firestore_client
        self._deadline_extractor = deadline_extractor
        self._deadline_service = deadline_service
        self._wellbeing_classifier = wellbeing_classifier
        self._wellbeing_service = wellbeing_service

    async def stream_chat(
        self,
        user_id: str,
        conversation_id: Optional[str],
        message: str,
    ) -> AsyncIterator[str]:
        """
        Execute a full chat turn: load history → RAG → stream LLM → persist.

        Yields:
            Token strings as they are generated by the LLM.
        """
        # 1. Resolve or create conversation
        if conversation_id is None:
            conversation_id = await self._create_conversation(user_id)

        # 2. Load recent chat history from Firestore (non-blocking)
        chat_history = await self._load_chat_history(
            user_id, conversation_id, limit=settings.RAG_CONTEXT_WINDOW
        )

        # 3. Persist the user message immediately (non-blocking)
        await self._save_message(user_id, conversation_id, "user", message)

        # 4. Build RAG-augmented prompt
        augmented_prompt = await self._rag.query(message, chat_history)

        # 5. Stream LLM response
        collected_response = ""
        try:
            async for token in self._llm.stream(
                prompt=augmented_prompt,
                system_instruction=BUREAUCRACY_SYSTEM_INSTRUCTION,
            ):
                collected_response += token
                yield token
        except LLMClientError as e:
            logger.error("LLM error during chat stream: %s", e.message)
            error_msg = f"\n\n⚠️ {e.message}"
            collected_response += error_msg
            yield error_msg

        # 6. Persist the full assistant response after streaming completes (non-blocking)
        await self._save_message(
            user_id, conversation_id, "assistant", collected_response
        )

        # 7. Update conversation metadata (non-blocking)
        await self._update_conversation_metadata(user_id, conversation_id)

        # 8. Extract deadlines from the response (post-processing)
        if (
            settings.ENABLE_DEADLINE_EXTRACTION
            and self._deadline_extractor is not None
            and self._deadline_service is not None
            and collected_response
            and not collected_response.startswith("\n\n⚠️")
        ):
            try:
                deadlines = await self._deadline_extractor.extract(collected_response)
                if deadlines:
                    await self._deadline_service.save_deadlines(
                        user_id, conversation_id, deadlines
                    )
            except Exception as e:
                logger.warning("Deadline extraction failed (non-fatal): %s", e)

        # 9. Wellbeing classification on USER message (fire-and-forget)
        if (
            settings.ENABLE_WELLBEING_CLASSIFICATION
            and self._wellbeing_classifier is not None
            and self._wellbeing_service is not None
            and message
        ):
            asyncio.create_task(
                self._classify_wellbeing(user_id, conversation_id, message)
            )

    async def _classify_wellbeing(
        self, user_id: str, conversation_id: str, message: str
    ) -> None:
        """Fire-and-forget wellbeing classification on user message."""
        try:
            classification = await self._wellbeing_classifier.classify(message)
            if classification and classification.signals:
                await self._wellbeing_service.process_classification(
                    user_id, conversation_id, message, classification
                )
        except Exception as e:
            logger.warning("Wellbeing classification failed (non-fatal): %s", e)

    def get_conversation_id(self) -> str:
        """Generate a new conversation ID."""
        return str(uuid.uuid4())

    async def _create_conversation(self, user_id: str) -> str:
        """Create a new conversation document in Firestore."""
        conversation_id = self.get_conversation_id()
        now = datetime.now(timezone.utc)

        if self._db is not None:
            try:
                await asyncio.to_thread(
                    self._create_conversation_sync,
                    user_id,
                    conversation_id,
                    now,
                )
            except Exception as e:
                logger.warning("Failed to create conversation in Firestore: %s", e)

        return conversation_id

    def _create_conversation_sync(
        self, user_id: str, conversation_id: str, now: datetime
    ) -> None:
        """Synchronous Firestore write — run via asyncio.to_thread."""
        conv_ref = (
            self._db.collection("users")
            .document(user_id)
            .collection("conversations")
            .document(conversation_id)
        )
        conv_ref.set(
            {
                "title": "New Conversation",
                "created_at": now,
                "updated_at": now,
                "message_count": 0,
            }
        )

    async def _load_chat_history(
        self, user_id: str, conversation_id: str, limit: int = 10
    ) -> list[dict]:
        """Load recent messages from Firestore for context (non-blocking)."""
        if self._db is None:
            return []

        try:
            return await asyncio.to_thread(
                self._load_chat_history_sync, user_id, conversation_id, limit
            )
        except Exception as e:
            logger.warning("Failed to load chat history: %s", e)
            return []

    def _load_chat_history_sync(
        self, user_id: str, conversation_id: str, limit: int
    ) -> list[dict]:
        """Synchronous Firestore read — run via asyncio.to_thread."""
        messages_ref = (
            self._db.collection("users")
            .document(user_id)
            .collection("conversations")
            .document(conversation_id)
            .collection("messages")
            .order_by("timestamp")
            .limit(limit)
        )
        docs = messages_ref.stream()
        return [
            {"role": doc.to_dict()["role"], "content": doc.to_dict()["content"]}
            for doc in docs
        ]

    async def _save_message(
        self,
        user_id: str,
        conversation_id: str,
        role: str,
        content: str,
        sources: Optional[list[str]] = None,
    ) -> None:
        """Persist a single message to Firestore (non-blocking)."""
        if self._db is None:
            return

        try:
            await asyncio.to_thread(
                self._save_message_sync,
                user_id,
                conversation_id,
                role,
                content,
                sources,
            )
        except Exception as e:
            logger.warning("Failed to save message to Firestore: %s", e)

    def _save_message_sync(
        self,
        user_id: str,
        conversation_id: str,
        role: str,
        content: str,
        sources: Optional[list[str]] = None,
    ) -> None:
        """Synchronous Firestore write — run via asyncio.to_thread."""
        msg_ref = (
            self._db.collection("users")
            .document(user_id)
            .collection("conversations")
            .document(conversation_id)
            .collection("messages")
            .document()
        )
        msg_ref.set(
            {
                "role": role,
                "content": content,
                "timestamp": datetime.now(timezone.utc),
                "sources": sources or [],
            }
        )

    async def _update_conversation_metadata(
        self, user_id: str, conversation_id: str
    ) -> None:
        """Update conversation metadata (non-blocking)."""
        if self._db is None:
            return

        try:
            await asyncio.to_thread(
                self._update_conversation_metadata_sync,
                user_id,
                conversation_id,
            )
        except Exception as e:
            logger.warning("Failed to update conversation metadata: %s", e)

    def _update_conversation_metadata_sync(
        self, user_id: str, conversation_id: str
    ) -> None:
        """Synchronous Firestore update — run via asyncio.to_thread."""
        conv_ref = (
            self._db.collection("users")
            .document(user_id)
            .collection("conversations")
            .document(conversation_id)
        )
        from google.cloud.firestore_v1 import Increment

        conv_ref.update(
            {
                "updated_at": datetime.now(timezone.utc),
                "message_count": Increment(2),  # user + assistant
            }
        )

    async def get_conversations(self, user_id: str) -> list[dict]:
        """List all conversations for a user."""
        if self._db is None:
            return []

        try:
            return await asyncio.to_thread(
                self._get_conversations_sync, user_id
            )
        except Exception as e:
            logger.warning("Failed to load conversations: %s", e)
            return []

    def _get_conversations_sync(self, user_id: str) -> list[dict]:
        """Synchronous Firestore read — run via asyncio.to_thread."""
        convs_ref = (
            self._db.collection("users")
            .document(user_id)
            .collection("conversations")
            .order_by("updated_at", direction="DESCENDING")
        )
        docs = convs_ref.stream()
        return [
            {"conversation_id": doc.id, **doc.to_dict()}
            for doc in docs
        ]
